package:
  name: imglib2-python-fat-jar
  version: 0.0.1_SNAPSHOT

source:
  git_url: https://github.com/hanslovsky/imglib2-python-fat-jar
  git_rev: master

build:
  number: 0

requirements:
 build:
   - openjdk >=8
   - apache-maven
   - imglib2-algorithm ==0.6.3_SNAPSHOT
   - imglib2-unsafe ==0.0.1_SNAPSHOT
 run:
   - openjdk >=8
   - python >=3
   - numpy
   - pyjnius-master
   - vigra

about:
  home: https://github.com/hanslovsky/imglib2-pthon-fat-jar
